name: web-to-md
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - requests
    - beautifulsoup4
    - openai
    - python-dotenv
    - html2text
    - flask
    - flask-cors